#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

echo "Creating mesh for air region"
blockMesh -region air > log.blockMesh.air 2>&1
createPatch -region air -overwrite > log.createPatch.air 2>&1
changeDictionary -region air > log.changeDictionary.air 2>&1

echo "Creating mesh for solid regions"
for i in leeward street windward
do
    blockMesh -region $i > log.blockMesh.$i 2>&1
    changeDictionary -region $i > log.changeDictionary.$i 2>&1
    setSet -region $i -noVTK -batch system/$i/setset.batch > log.setSet.$i 2>&1
done

echo "Creating vegetation region for radiation calculation"
cp -r constant/air/polyMesh/ constant/vegetation/polyMesh
topoSet -region vegetation -dict system/../air/topoSetDict
splitMeshRegions -region vegetation -cellZones
rm -r constant/vegetation/polyMesh
cp -r 3600/region1/polyMesh constant/vegetation/
rm -r 3600
rm -r system/vegetation/trees system/vegetation/region*
rm 0/vegetation/cellToRegion*
createPatch -region vegetation -overwrite
changeDictionary -region vegetation
cp 0/vegetation.bckp/* 0/vegetation/.
cp 0/air.bckp/LAD 0/air/.
topoSet -region air
setFields -region air

# ----------------------------------------------------------------- end-of-file
