#!/usr/bin/env python3
"""
ParaView Python script for visualizing heatedCavity at time 200
Generated by plot_fields.py

Usage in ParaView:
    Tools → Python Shell → Run Script
    Or: paraview --script=visualize_200.py
"""

import paraview.simple as pv

# Clear any existing views
pv.Disconnect()
pv.Connect()

# Create a new render view
renderView = pv.CreateView('RenderView')
renderView.ViewSize = [1200, 800]
renderView.Background = [0.32, 0.34, 0.43]

# Open the case
case_file = 'cases/heatedCavity/heatedCavity.foam'
reader = pv.OpenFOAMReader(FileName=case_file)
reader.CaseType = 'Decomposed Case'
reader.EnablePatches = 1

# Set active time
reader.MeshRegions = ['internalMesh']
reader.CellArrays = ['U', 'p', 'T']
reader.TimeStep = 200

# Create display
display = pv.Show(reader, renderView)
display.Representation = 'Surface'
display.ColorArrayName = ['CELLS', 'T']
display.LookupTable = pv.GetColorTransferFunction('T')

# Create temperature slice
slice1 = pv.Slice(Input=reader)
slice1.SliceType = 'Plane'
slice1.SliceType.Origin = [0.5, 0.5, 0.005]
slice1.SliceType.Normal = [0.0, 0.0, 1.0]

sliceDisplay = pv.Show(slice1, renderView)
sliceDisplay.Representation = 'Surface'
sliceDisplay.ColorArrayName = ['CELLS', 'T']
sliceDisplay.LookupTable = pv.GetColorTransferFunction('T')

# Create velocity vectors
glyph1 = pv.Glyph(Input=slice1, GlyphType='Arrow')
glyph1.OrientationArray = ['CELLS', 'U']
glyph1.ScaleArray = ['CELLS', 'U']
glyph1.ScaleFactor = 0.1
glyph1.GlyphMode = 'Every Nth Point'
glyph1.Stride = 5

glyphDisplay = pv.Show(glyph1, renderView)
glyphDisplay.ColorArrayName = ['CELLS', 'T']

# Reset camera
renderView.ResetCamera()

# Render
renderView.Update()
pv.Render()

print("Visualization ready!")
print("Adjust views and save state file if needed.")
