#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

echo "Creating mesh for air region"
blockMesh -region air > log.blockMesh.air 2>&1
createPatch -region air -overwrite > log.createPatch.air 2>&1
changeDictionary -region air > log.changeDictionary.air 2>&1

echo "Creating mesh for solid regions"
for i in leeward street windward
do
    blockMesh -region $i > log.blockMesh.$i 2>&1
    changeDictionary -region $i > log.changeDictionary.$i 2>&1
    setSet -region $i -noVTK -batch system/$i/setset.batch > log.setSet.$i 2>&1
done

# ----------------------------------------------------------------- end-of-file
