#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
makeType=${1:-libso}

set -x

wclean buildingMaterialModel
wclean solarLoadModel
wclean simpleControlFluid
wclean grassModel
wclean turbulenceModels
wclean vegetationModels
wclean parallel/distributed
wclean blendingLayer
