#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
makeType=${1:-libso}

set -x

wmake $makeType buildingMaterialModel
wmake $makeType solarLoadModel
wmake $makeType simpleControlFluid
wmake $makeType grassModel
wmake $makeType turbulenceModels
wmake $makeType vegetationModels
wmake $makeType parallel/distributed
wmake $makeType blendingLayer
