#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

blockMesh > log.blockMesh 2>&1
surfaceFeatures > log.surfaceFeatures 2>&1

echo "Creating mesh for air region"
cp -r constant/polyMesh constant/polyMesh.bckp
cp system/snappyHexMeshDict.air system/snappyHexMeshDict
snappyHexMesh -overwrite > log.snappyHexMesh.air 2>&1
rm -rf constant/air/polyMesh
mv constant/polyMesh constant/air/
changeDictionary -region air > log.changeDictionary.air 2>&1

#######################
echo "Creating mesh for vegetation region"
cp -r constant/polyMesh.bckp constant/polyMesh
cp system/snappyHexMeshDict.veg system/snappyHexMeshDict
snappyHexMesh -overwrite > log.snappyHexMesh.veg 2>&1
rm -rf constant/vegetation/polyMesh
mv constant/polyMesh constant/vegetation/
createPatch -region vegetation -overwrite > log.createPatch.veg 2>&1
changeDictionary -region vegetation > log.changeDictionary.veg 2>&1
cp -r 0/vegetation.bckp 0/vegetation
rm -rf constant/polyMesh.bckp

#######################
echo "Creating mesh for buildings region"
i=buildings
cp system/${i}/extrudeMeshDict_${i}_layer1 system/extrudeMeshDict
extrudeMesh > log.extrudeMesh.${i}1 2>&1

cp system/${i}/extrudeMeshDict_${i}_layer2 system/extrudeMeshDict
extrudeMesh > log.extrudeMesh.${i}2 2>&1
mv constant/polyMesh/sets/addedCells.gz constant/polyMesh/sets/addedCells_layer2.gz

rm -rf constant/$i/polyMesh
mv constant/polyMesh constant/$i/
createPatch -region $i -overwrite > log.createPatch.$i 2>&1
changeDictionary -region $i > log.changeDictionary.$i 2>&1
topoSet -region $i > log.topoSet.$i 2>&1

#######################
echo "Creating mesh for ground region"
i=ground
cp system/${i}/extrudeMeshDict_${i}_layer1 system/extrudeMeshDict
extrudeMesh > log.extrudeMesh.${i}1 2>&1

cp system/${i}/extrudeMeshDict_${i}_layer2 system/extrudeMeshDict
extrudeMesh > log.extrudeMesh.${i}2 2>&1
mv constant/polyMesh/sets/addedCells.gz constant/polyMesh/sets/addedCells_layer2.gz

rm -rf constant/$i/polyMesh
mv constant/polyMesh constant/$i/
createPatch -region $i -overwrite > log.createPatch.$i 2>&1
changeDictionary -region $i > log.changeDictionary.$i 2>&1
topoSet -region $i > log.topoSet.$i 2>&1

#######################
echo "Setting LAD values"
topoSet -region air > log.topoSet.air 2>&1
cp 0/air.bckp/LAD 0/air/.
setFields -region air > log.setFields.air 2>&1

# ----------------------------------------------------------------- end-of-file
