#!/usr/bin/env python3
"""
Generate plots from OpenFOAM case results.

This script uses foamToVTK to convert OpenFOAM data to VTK format,
then creates publication-ready plots.

Usage:
    python scripts/postprocess/plot_fields.py <case-directory> [time-directory]

Example:
    python scripts/postprocess/plot_fields.py custom_cases/heatedCavity 200
"""

import sys
import os
import subprocess
from pathlib import Path

def run_foamToVTK(case_dir, time_dir=None):
    """Run foamToVTK to convert OpenFOAM data to VTK."""
    case_path = Path(case_dir)
    
    cmd = ['foamToVTK']
    if time_dir:
        cmd.extend(['-time', time_dir])
    
    print(f"Running foamToVTK in {case_path}...")
    result = subprocess.run(
        cmd,
        cwd=case_path,
        capture_output=True,
        text=True
    )
    
    if result.returncode != 0:
        print(f"Error running foamToVTK: {result.stderr}")
        return False
    
    print("✓ VTK files generated")
    return True

def create_paraview_script(case_dir, time_dir):
    """Create a ParaView Python script for visualization."""
    case_path = Path(case_dir)
    case_name = case_path.name
    script_path = case_path / f"visualize_{time_dir}.py"
    
    script_content = f'''#!/usr/bin/env python3
"""
ParaView Python script for visualizing {case_name} at time {time_dir}
Generated by plot_fields.py

Usage in ParaView:
    Tools → Python Shell → Run Script
    Or: paraview --script=visualize_{time_dir}.py
"""

import paraview.simple as pv

# Clear any existing views
pv.Disconnect()
pv.Connect()

# Create a new render view
renderView = pv.CreateView('RenderView')
renderView.ViewSize = [1200, 800]
renderView.Background = [0.32, 0.34, 0.43]

# Open the case
case_file = '{case_path / f"{case_name}.foam"}'
reader = pv.OpenFOAMReader(FileName=case_file)
reader.CaseType = 'Decomposed Case'
reader.EnablePatches = 1

# Set active time
reader.MeshRegions = ['internalMesh']
reader.CellArrays = ['U', 'p', 'T']
reader.TimeStep = {time_dir}

# Create display
display = pv.Show(reader, renderView)
display.Representation = 'Surface'
display.ColorArrayName = ['CELLS', 'T']
display.LookupTable = pv.GetColorTransferFunction('T')

# Create temperature slice
slice1 = pv.Slice(Input=reader)
slice1.SliceType = 'Plane'
slice1.SliceType.Origin = [0.5, 0.5, 0.005]
slice1.SliceType.Normal = [0.0, 0.0, 1.0]

sliceDisplay = pv.Show(slice1, renderView)
sliceDisplay.Representation = 'Surface'
sliceDisplay.ColorArrayName = ['CELLS', 'T']
sliceDisplay.LookupTable = pv.GetColorTransferFunction('T')

# Create velocity vectors
glyph1 = pv.Glyph(Input=slice1, GlyphType='Arrow')
glyph1.OrientationArray = ['CELLS', 'U']
glyph1.ScaleArray = ['CELLS', 'U']
glyph1.ScaleFactor = 0.1
glyph1.GlyphMode = 'Every Nth Point'
glyph1.Stride = 5

glyphDisplay = pv.Show(glyph1, renderView)
glyphDisplay.ColorArrayName = ['CELLS', 'T']

# Reset camera
renderView.ResetCamera()

# Render
renderView.Update()
pv.Render()

print("Visualization ready!")
print("Adjust views and save state file if needed.")
'''
    
    with open(script_path, 'w') as f:
        f.write(script_content)
    
    os.chmod(script_path, 0o755)
    print(f"✓ ParaView script created: {script_path}")
    return script_path

def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)
    
    case_dir = sys.argv[1]
    time_dir = sys.argv[2] if len(sys.argv) > 2 else None
    
    case_path = Path(case_dir)
    if not case_path.exists():
        print(f"Error: Case directory '{case_dir}' does not exist")
        sys.exit(1)
    
    # Find latest time directory if not specified
    if time_dir is None:
        time_dirs = [d for d in case_path.iterdir() 
                    if d.is_dir() and d.name.replace('.', '').replace('-', '').isdigit()]
        if not time_dirs:
            print(f"Error: No time directories found in '{case_dir}'")
            sys.exit(1)
        time_dir = max(time_dirs, key=lambda x: float(x.name)).name
        print(f"Using latest time directory: {time_dir}")
    
    # Ensure .foam file exists
    foam_file = case_path / f"{case_path.name}.foam"
    if not foam_file.exists():
        foam_file.touch()
        print(f"✓ Created ParaView case file: {foam_file}")
    
    # Run foamToVTK (requires OpenFOAM environment)
    print("\nNote: foamToVTK requires OpenFOAM environment.")
    print("Run this inside the Docker container or with OpenFOAM sourced.")
    print("Example:")
    print(f"  docker compose run --rm dev bash -c '")
    print(f"    source /opt/openfoam8/etc/bashrc &&")
    print(f"    cd /workspace/{case_dir} &&")
    print(f"    foamToVTK -time {time_dir}")
    print(f"  '")
    
    # Create ParaView Python script
    script_path = create_paraview_script(case_dir, time_dir)
    
    print(f"\n✓ Visualization setup complete!")
    print(f"\nTo visualize:")
    print(f"  1. Start ParaView: docker compose run --rm dev paraview")
    print(f"  2. Load the case file: {foam_file}")
    print(f"  3. Or run the script: paraview --script={script_path}")

if __name__ == '__main__':
    main()

